services:
  db:
    image: postgres:16.10-alpine3.22
    container_name: blog_db
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
      POSTGRES_DB: blog
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    ports:
      - "5432:5432"
    command:
      - postgres
      - -c
      - logging_collector=on
      - -c
      - log_directory=/var/log/postgresql
      - -c
      - log_filename=postgresql.log
      - -c
      - log_statement=all
      - -c
      - log_min_duration_statement=0
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U blog_user -d blog" ]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: blog_app
    image: blog-server:latest
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/blogdb
    volumes:
      - ./logs/app:/var/log/app

volumes:
  postgres-data: